### ISSUE TITLE
선택지 미선택시 next 버튼 비활성화

### ISSUE THREAD

**Issue by Minchelin42** [Dream-Catch/Balance-Catch-iOS#29]
## Description
- 현재 UserFirstSelectView()와 UserFinalSelectView()에서 선택하지 않아도 다음 view로 넘어감
- 2가지 선택지 중 1가지를 선택해야만 next 버튼 활성화시켜야 함

**Comment by Minny27** [comment]
iOS 16.0 버전 이상부터 사용하는 NavigationStack을 이용해서 문제를 해결함.
