### ISSUE TITLE
서버에 요청 중 네트워크 연결 끊겼을 때 처리

### ISSUE THREAD

**Issue by Minny27** [Dream-Catch/Balance-Catch-iOS#51]
## Description
- 네트워크 연결이 끊겼을 때 어떻게 처리할 지 고민할 것

**Comment by Minny27** [comment]
네트워크 연결이 끊겼을 때 다음과 같은 에러가 발생하면서 데이터를 불러오지 못함
<img src="https://github.com/Dream-Catch/Balance-Catch-iOS/assets/68800789/16713a6d-7a69-4753-be4d-b04745bb6553" width=60%>

**Comment by choo121600** [comment]
저게 네트워크 연결이 안되어 있을 때도 직전에 받아온 데이터를 보여줘야 경우엔 내부 캐시나 mock 데이터로 값을 보여주는 거로 처리하긴 합니다.
저희는 빙글 빙글 돌다가 몇초 이상이면 네트워크 확인해달라고 해도 괜찮을 듯 하고요

**Comment by Minny27** [comment]
저도 같은 생각입니다. 재요청 2 ~ 3회 실시하고 안 되면 네트워크 연결해달라는 팝업을 띄우거나 하는 방식으로 해야할 거같아요.
만약 이미 응답받은 데이터가 있으면 앱 내부 디비에 저장해서 사용하는 것도 고려해보면 좋을 거 같네요

**Comment by Minny27** [comment]
현재 코드에서는 서버로부터 응답을 받아오거나 에러가 발생할 때, 로딩 뷰를 멈추도록 되어있음.
그래서 네트워크 에러가 발생하면 앱 크래시가 발생함.
스크린샷은 다음과 같음.
<img src="https://github.com/Dream-Catch/Balance-Catch-iOS/assets/68800789/7c567b84-7226-4bb2-ae19-ad216ef931f9" width=60%>

타임 아웃을 고려하거나 error를 리턴받았을 때, 재시도 버튼을 만드는 것도 좋아보임.

**Comment by choo121600** [comment]
에러를 리턴해주면 에러를 받았을때 네트워크 확인 후 재시도 이런 alert창이 떠주는것도 좋아보이긴하네요

**Comment by Minny27** [comment]
alert 좋은거 같아요! 알럿창의 왼쪽 버튼은 **설정**, 오른쪽 버튼은 **재시도**로 해볼까 하는데 어떠신지요

**Comment by Minny27** [comment]
질문 get은 잘 처리되나 질문 좋아요 화면에서 버튼 클릭 시에는 바로 다음 뷰를 띄우기 때문에 제대로 동작하지 않습니다..
이 부분은 차후에 리팩토링 하겠습니다
